general {
    base_exp_dir = ./exp/belhe/ingp
    recording = [
        ./,
        ./data,
        ./net,
        ./runner,
    ]
    random_seed = 2025
}

dataset {}

train {
    learning_rate = 5e-4
    learning_rate_ngp = 2.5e-3
    learning_rate_alpha = 0.015
    end_iter = 300000

    xmin = 0.00
    xmax = 1.00
    ymin = 0.00
    ymax = 1.00

    sample_size = 1024
    warm_up_end = 5000

    save_freq = 10000
    report_freq = 100
    val_freq = 2500
}

network {
    d_in = 2
    d_out = 1

    input_encoding {
        flavour = ingp

        otype = "HashGrid"
        n_levels = 8
        n_features_per_level = 2
        log2_hashmap_size = 19
        base_resolution = 16
        per_level_scale = 2.0
    }

    mlp {
        d_hidden = 256
        n_layers = 4
        nonlinearity = softplus
        weight_norm = true
    }
}

visual {
    xmin =  0.374   # 0.00
    xmax =  0.464   # 1.00
    ymin =  0.518   # 0.00
    ymax =  0.608   # 1.00
    contour_levels = [-0.90, -0.80, -0.70, -0.60, -0.50, -0.40, -0.30, -0.20]
    vmin = -1.00
    vmax = -0.10
}

eval {
    xmin =  0.00
    xmax =  1.00
    ymin =  0.00
    ymax =  1.00
}
