general {
    base_exp_dir = ./exp/geodesic/pe
    recording = [
        ./,
        ./data,
        ./net,
        ./runner,
    ]
    random_seed = 2025
}

dataset {
    name = geodesic
    cx = 1.0
    radius = 0.5
}

train {
    learning_rate = 5e-4
    learning_rate_alpha = 0.015
    end_iter = 300000

    xmin =  1.51
    xmax =  2.11
    ymin = -0.3
    ymax =  0.3

    sample_size = 1024
    warm_up_end = 5000

    save_freq = 10000
    report_freq = 100
    val_freq = 2500
}

network {
    d_in = 2
    d_out = 1

    input_encoding {
        flavour = pe
        multires = 4
    }

    mlp {
        d_hidden = 256
        n_layers = 4
        nonlinearity = softplus
        weight_norm = true

        shift = 2.06
    }
}

visual {
    xmin =  1.55
    xmax =  1.95
    ymin = -0.025
    ymax =  0.025
    contour_levels = [1.94, 1.97, 2.00, 2.03, 2.06, 2.09, 2.12, 2.15, 2.18]
    vmin =  0.00
    vmax =  2.40
}

eval {
    xmin =  1.55
    xmax =  1.95
    ymin = -0.005
    ymax =  0.005
}
